export const ADD_WISHLIST_ITEM = "ADD_WISHLIST_ITEM";
export const REMOVE_WISHLIST_ITEM = "REMOVE_WISHLIST_ITEM";
export const CLEAR_WISHLIST = "CLEAR_FROM_WISHLIST";
export const FETCH_WISHLIST_START = "FETCH_WISHLIST_START";
export const FETCH_WISHLIST_SUCCESS = "FETCH_WISHLIST_SUCCESS";
export const FETCH_WISHLIST_FAILURE = "FETCH_WISHLIST_FAILURE";
export const RESET_WISHLIST = "RESET_WISHLIST";
